#!/bin/sh
tmux new-session -n jibreel \; \
	send-keys 'htop' C-m \; \
	new-window -n Editor \; \
	send-keys 'vi' C-m \; \
	split-window -v -p 21 \; \
	new-window -n Git \; \
	select-window -t 1 \; \
	select-pane -t 0 \;
